% Perfil 3: Foco em Criatividade, Design e Web/Jogos.
% Esperado: desenvolvimento_web e ciencia_de_dados no topo.
resposta(1, n).   % 'Voce tem afinidade com matematica?', 'matematica'
resposta(2, n).   % 'Voce gosta de logica e raciocinio?', 'logica'
resposta(3, s).   % 'Voce tem interesse em programacao?', 'programacao'
resposta(4, s).   % 'Voce aprecia design e criatividade visual?', 'design_visual'
resposta(5, n).   % 'Voce tem atencao a detalhes?', 'atencao_a_detalhes'
resposta(6, n).   % 'Voce gosta de trabalhar com redes e infraestrutura?', 'redes'
resposta(7, n).   % 'Voce gosta de analisar e interpretar dados?', 'analise_dados'
resposta(8, n).   % 'Voce tem facilidade com estatistica?', 'matematica_estatistica'
resposta(9, n).   % 'Voce gosta de resolver problemas tecnicos?', 'resolucao_problemas'
resposta(10, n).  % 'Voce entende de hardware?', 'hardware'
resposta(11, n).  % 'Voce se interessa por automacao de processos?', 'automatizacao'
resposta(12, n).  % 'Voce tem conhecimentos em computacao em nuvem?', 'conhecimento_cloud'
resposta(13, s).  % 'Voce tem criatividade para design e desenvolvimento de jogos?', 'criatividade'
resposta(14, n).  % 'Voce tem interesse e conhecimento em aprendizado de maquina?', 'aprendizado_maquina'
resposta(15, s).  % 'Voce se interessa por usabilidade e experiencia do usuario?', 'usabilidade'
resposta(16, n).  % 'Voce gosta de trabalhar pensando na seguranca com criptografia?', 'criptografia'
resposta(17, s).  % 'Voce tem facilidade para criar visualizacoes de dados claras e uteis?', 'visualizacao_de_dados'
resposta(18, n).  % 'Voce sabe configurar servidores e gerenciar servicos?', 'configuracao_servidores'
resposta(19, n).  % 'Voce tem experiencia com gerenciamento de configuracoes em sistemas?', 'gerenciamento_de_configuracoes'
resposta(20, s).  % 'Voce gosta de trabalhar com design de som e efeitos para jogos?', 'design_de_som'
